---
- hosts: TEST
  gather_facts: false
  connection: ssh

  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_pass: <enable password>

  tasks:
  - name: configure interface settings
    ios_config:
      lines:
        - description test interface
        - ip address 172.31.1.1 255.255.255.0
      parents: interface GigabitEthernet0/1

~
~